### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### canel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "7eaca654d0ba4fe1a3fd55e43df26eaa",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/382b4d82b11a4368bdaf0a893c4cb4f8